const DataMap=new WeakMap(),ProxyCache=new WeakMap(),RawCache=new WeakMap(),CleanupMap=new WeakMap();
const pendingUpdates=new Set();let isFlushing=false,isBatching=false;const fnStack=[];
const SVG_NS="http://www.w3.org/2000/svg",STORE=Symbol('store');
function DataProxy(obj){if(typeof obj!=="object"||obj===null)return obj;if(ProxyCache.has(obj))return ProxyCache.get(obj);const MUTATORS=new Set(["push","pop","shift","unshift","splice","sort","reverse"]);const proxy=new Proxy(obj,{get(t,k,r){if(Array.isArray(t)&&MUTATORS.has(k))return(...a)=>{const res=t[k](...a);trigger(t,"*");trigger(t,"length");return res};const active=fnStack.at(-1);if(active){let d=DataMap.get(t)??(DataMap.set(t,new Map),DataMap.get(t));let s=d.get(k)??(d.set(k,new Set),d.get(k));s.add(active)}const v=Reflect.get(t,k,r);return v&&typeof v==="object"?DataProxy(v):v},set(t,k,v,r){const raw=RawCache.get(v)??v,old=t[k],res=Reflect.set(t,k,raw,r);if(old!==raw){trigger(t,k);if(Array.isArray(t)&&typeof k==="string"&&/^\d+$/.test(k)){trigger(t,"length");trigger(t,"*")}}return res}});ProxyCache.set(obj,proxy);RawCache.set(proxy,obj);return proxy}
export function domData(init,actions={}){const data=DataProxy(init),store={[STORE]:true,data};for(const[n,fn]of Object.entries(actions))store[n]=(...a)=>batch(()=>fn(data,...a));return store}
function trigger(t,k){const d=DataMap.get(t);if(!d)return;const run=s=>s?.forEach(f=>pendingUpdates.add(f));run(d.get(k));if(k!=='*')run(d.get('*'));if(pendingUpdates.size>0&&!isBatching&&!isFlushing)queueMicrotask(flush);}
function flush(){if(isFlushing)return;isFlushing=true;const fl=[...pendingUpdates];pendingUpdates.clear();for(const f of fl){try{f();}catch(e){console.error(e);}}isFlushing=false;if(pendingUpdates.size>0)queueMicrotask(flush);}
function autoUpdate(fn){let active=true;const w=()=>{if(!active)return;fnStack.push(w);try{return fn();}finally{fnStack.pop();}};w.dispose=()=>{active=false;pendingUpdates.delete(w);};w();return w;}
function batch(fn){const was=isBatching;isBatching=true;try{return fn();}finally{isBatching=was;if(!was&&pendingUpdates.size>0)queueMicrotask(flush);}}
function onDestroy(el,fn){let s=CleanupMap.get(el)??(CleanupMap.set(el,new Set()),CleanupMap.get(el));s.add(fn);}
function triggerDestroy(el){if(el.nodeType!==1)return;el.querySelectorAll('*').forEach(triggerDestroy);const f=CleanupMap.get(el);if(f){f.forEach(fn=>{try{fn();}catch(e){}});CleanupMap.delete(el);}}
function setDOMValue(el,k,v,svg){if(!svg&&(k==='value'||k==='checked')){el[k]=v;}else if(!svg&&k in el&&typeof el[k]!=='object'){el[k]=v;}else{el.setAttribute(k,v);}}
function applyClass(el,v,svg){if(v&&typeof v==='object'&&!Array.isArray(v)){Object.entries(v).forEach(([c,on])=>el.classList.toggle(c,!!on));}else{const cn=Array.isArray(v)?v.filter(Boolean).join(' '):(v??'');svg?el.setAttribute('class',cn):(el.className=cn);}}
function applyStyle(el,v){if(v&&typeof v==='object'){for(const[k,p]of Object.entries(v)){if(k.startsWith('--'))el.style.setProperty(k,p);else el.style[k]=p;}}else{el.style.cssText=v??'';}}
function fragment(children,isSVG=false){const f=document.createDocumentFragment();flattenChildren(f,children,isSVG);return f;}
function flattenChildren(parent,arr,isSVG=false){const lc=new Map;for(let i=0;i<arr.length;i++){const child=arr[i];if(isStore(child)&&typeof arr[i+1]==="function"){const res=elist(child,arr[i+1]);if(res instanceof DocumentFragment)parent.appendChild(res);else parent.appendChild(res);i++;continue}if(Array.isArray(child)){flattenChildren(parent,child,isSVG)}else if(typeof child==="function"){let oldItems=[],textNode=null;const anchor=document.createTextNode("");parent.appendChild(anchor);const eff=autoUpdate(()=>{let res=child(isSVG);if(res instanceof Node)res=[res];if(Array.isArray(res)){if(textNode){textNode.remove();textNode=null}reconcile(parent,anchor,oldItems,res,lc);oldItems=[...res]}else{if(oldItems.length>0){for(const i of oldItems){const n=lc.get(i);if(n){if(n.nodeType===1)triggerDestroy(n);n.remove()}}oldItems=[]}if(!textNode){textNode=document.createTextNode("");anchor.before(textNode)}textNode.textContent=res==null||res===false?"":String(res)}});onDestroy(parent instanceof Element?parent:anchor,()=>{eff.dispose();textNode?.remove();if(anchor.parentNode)anchor.remove()})}else if(child instanceof Node){parent.appendChild(child)}else if(child!=null&&child!==false){parent.appendChild(document.createTextNode(String(child)))}}}
function lis(seq){const n=seq.length,result=[],par=new Array(n).fill(-1);for(let i=0;i<n;i++){if(seq[i]===-1)continue;let lo=0,hi=result.length;while(lo<hi){const m=(lo+hi)>>1;if(seq[result[m]]<seq[i])lo=m+1;else hi=m;}if(lo>0)par[i]=result[lo-1];result[lo]=i;}const stable=new Set();let cur=result.at(-1);while(cur!=null&&cur!==-1){stable.add(cur);cur=par[cur];}return stable;}
function reconcile(parent,anchor,oldItems,newItems,cache){const oldMap=new Map(oldItems.map((it,i)=>[it,i])),newSet=new Set(newItems);for(const it of oldItems){if(!newSet.has(it)){const n=it instanceof Node?it:cache.get(it);if(n){if(n.nodeType===1)triggerDestroy(n);n.remove()}cache.delete(it)}}for(const it of newItems){if(!cache.has(it)){const n=it instanceof Node?it:document.createTextNode(String(it));cache.set(it,n)}}const oi=newItems.map(it=>oldMap.has(it)?oldMap.get(it):-1),stable=lis(oi);for(let i=newItems.length-1;i>=0;i--){if(stable.has(i))continue;const n=cache.get(newItems[i]),bef=i+1<newItems.length?cache.get(newItems[i+1])??anchor:anchor;if(n)parent.insertBefore(n,bef)}}
function keyList(getItems,keyFn,renderFn){const nc=new Map,pk=[];return isSVG=>{const items=getItems(),nk=[],ns=new Set,res=[];for(let i=0;i<items.length;i++){const it=items[i],k=keyFn(it,i);nk.push(k);ns.add(k);if(!nc.has(k)){const r=renderFn(it,i,isSVG);nc.set(k,r instanceof DocumentFragment?Array.from(r.childNodes):r)}const c=nc.get(k);if(Array.isArray(c))res.push(...c);else res.push(c)}for(const k of pk){if(!ns.has(k)){const ns2=[].concat(nc.get(k));ns2.forEach(n=>{if(n.nodeType===1)triggerDestroy(n)});nc.delete(k)}}pk.length=0;pk.push(...nk);return res}}
const isStore=d=>d?.[STORE]===true&&!Array.isArray(d.data);
const isArrayStore=d=>d?.[STORE]===true&&Array.isArray(d.data);
function elist(data,templateFn,parentNode,options={}){let content;if(isArrayStore(data)){content=keyList(()=>data.data,(it,i)=>it?.id??it?.key??i,(it,i,svg)=>templateFn(it,i))}else if(isStore(data)){content=()=>templateFn(data.data)}else if(Array.isArray(data)){content=data.map((it,i)=>templateFn(it,i))}else if(typeof data==="string"||data instanceof Node){content=data}else{throw new TypeError(`elist: unrecognised data \u2014 ${typeof data}`)}const items=Array.isArray(content)?content:[content];if(!parentNode)return fragment(items);flattenChildren(parentNode,items);return parentNode}
const isList = (val) => isArrayStore(val) || (typeof val === 'object' && val?.isList);
function setAttr(el, k, v, isSVG) { if (k === 'class' || k === 'className') applyClass(el, v, isSVG); else if (k === 'style') applyStyle(el, v); else setDOMValue(el, k, v, isSVG); };
function makeEl(tag,props,children,isSVG){const el=isSVG?document.createElementNS("http://www.w3.org/2000/svg",tag):document.createElement(tag);for(const[k,v]of Object.entries(props)){if(k.startsWith("on")){const evt=k.slice(2).toLowerCase();if(typeof v==="function"){if(evt==="create")v(el);else if(evt==="destroy")onDestroy(el,v);else{el.addEventListener(evt,v);onDestroy(el,()=>el.removeEventListener(evt,v))}}continue}if(typeof v==="function"){const eff=autoUpdate(()=>setAttr(el,k,v(isSVG),isSVG));onDestroy(el,()=>eff.dispose())}else{setAttr(el,k,v,isSVG)}}flattenChildren(el,children,isSVG);return el}
export function el(sel,...args){let props=args[0],children=args.slice(1);if(props==null||typeof props!=="object"||Array.isArray(props)||props instanceof Node||typeof props==="function"){children=args;props={}}const parts=sel.match(/([a-zA-Z0-9-_]+)|(\.[a-zA-Z0-9-_]+)|(#[a-zA-Z0-9-_]+)/g)??[];const tag=parts.find(p=>!p.startsWith(".")&&!p.startsWith("#"))??"div";const classes=parts.filter(p=>p.startsWith(".")).map(p=>p.slice(1));const id=parts.find(p=>p.startsWith("#"))?.slice(1);const merged={...props};if(id&&!merged.id)merged.id=id;if(classes.length){const base=props.class??props.className;merged.class=base?`${base} ${classes.join(" ")}`:classes.join(" ");delete merged.className}return makeEl(tag,merged,children,false)}
export function svg(tag,props={},...ch){if(typeof tag!=="string"){const isProps=tag!=null&&typeof tag==="object"&&!Array.isArray(tag);return makeEl("svg",isProps?{xmlns:"http://www.w3.org/2000/svg",...tag}:{xmlns:"http://www.w3.org/2000/svg"},isProps?[props,...ch]:[tag,props,...ch],true)}return makeEl(tag,props,ch,true)}
